### ISSUE TITLE
lumicks pytest() failing

### ISSUE THREAD

**Issue by rjakielski** [lumicks/pylake#159]
pytest() returns 4 failed tests/358 upon downloading following anaconda (MacOS) instructions (https://lumicks-pylake.readthedocs.io/en/stable/install.html). These tests are: 

FAILED ../../opt/anaconda3/envs/pylake/lib/python3.9/site-packages/lumicks/pylake/tests/test_kymo.py::test_save_tiff[MockDataFile_v2]
FAILED ../../opt/anaconda3/envs/pylake/lib/python3.9/site-packages/lumicks/pylake/tests/test_scan.py::test_save_tiff[MockDataFile_v2]
FAILED ../../opt/anaconda3/envs/pylake/lib/python3.9/site-packages/lumicks/pylake/tests/test_image.py::test_int_tiff
FAILED ../../opt/anaconda3/envs/pylake/lib/python3.9/site-packages/lumicks/pylake/tests/test_image.py::test_float_tiff

i've gone ahead and removed the pylake envi and tried re-installing several times. My current python --version is 3.9.6. Are there any hidden steps/dependencies not explicitly noted in the instructions that I might be missing that could cause tests to fail?

**Comment by JoepVanlier** [comment]
I'd have to see the full traceback to be sure, but I suspect these failures come from having installed the latest version of `tifffile`. If I'm correct, the error you see in the traceback should mention a `DeprecationWarning` rather than an exception. In the latest version of the `tifffile` package they deprecated automatically inferring the image type. We already have a fix for this (see https://github.com/lumicks/pylake/pull/158), which will ship with the next release of Pylake.

For now, if you want those tests to pass, downgrading `tifffile` to `2021.6.14` should fix the problem. Note though that if it is indeed only a `DeprecationWarning`, it can safely be ignored.

**Comment by rjakielski** [comment]
the traceback relating for all 4 failures does throw a `DeprecationWarning` referring to tiffile. Thank you!
